### ISSUE TITLE
Bilibili HTML5 Player History

### ISSUE THREAD

**Issue by Aqours** [Aqours/Aqours.github.io#5]
> 哔哩哔哩 HTML5 播放器的发展史，主要包括架构迁移、整体的性能优化、面临的问题及解决方案。

## Infrastructure History
> 基础架构发展史

HTML5 播放器的原型版本是用 ES5 + jQuery 写出来的，代码的打包方案用的是 gulp + browserify + [webpack]。flv.js 的横空出世，提供了浏览器解码 FLV 视频格式的方案，同时 flv.js 的打包方案也沿用了播放器的那一套。可是为什么工具链中会夹杂着 webpack 呢？在当时，webpack 主要用来把字体和图片文件打包在生成的播放器文件中。

此后经历过一次改革，把 ES5 完全迁移到 TypeScript，同时 browserify 被 webpack 完全取代。但是因为是迁移自旧代码，因此 TypeScript 代码的类型写的相当松散，诸多类型都是以 `any` 标注的。并且由于要使用 google-closure-compiler 的二压，即高级压缩模式，导致一些实用的 TypeScript 特性都被封禁掉了。

当前，以去除 google-closure-compiler 的二压模式为前提，设计了一套实验性的架构方案，这个方案没有用于线上，暂且不提。

**Comment by xqq** [comment]
其实 gulp+browserify 脚本最早是我写的，然后主站播放器拿过去用了

好奇 tsc 之后有没有跑 babel

**Comment by Aqours** [comment]
原来如此。tsc 直接到 es5，不走 babel。

**Comment by xqq** [comment]
印象中这么做的话是对标 lib.es5.d.ts，不能用 es6 方法，比如 `Object.assign()` 等

**Comment by Aqours** [comment]
嗯。babel 本身也不转换 Object.assign，和 ts 是一样的，不过 babel 可以通过 transform plugin 来转换，ts 的话需要自己引入。
